searchSpaceFile: search_space.json
trialCommand: python mnist.py 
trialCodeDirectory: .
trialGpuNumber: 1
trialConcurrency: 2
maxTrialNumber: 10
maxExperimentDuration: 1h
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: false
